// Representative intake payloads for each of the 8 CONTACT TYPES.
// Used by the test runner and useful for manual curl testing.

export const payloads = {
  youth: {
    name: 'Test',
    fullName: 'Jaylen Carter',
    email: 'jaylen.youth@example.com',
    phone: '(513) 555-0107',
    age: 13,
    category: 'Youth',
    interest: 'YEP cohort',
    parentName: 'Tasha Carter',
    parentEmail: 'tasha.carter@example.com',
    parentPhone: '513-555-0108',
    source: 'website-intake',
    consent: 'yes',
    message: 'I want to join YEP and learn how to start a business.',
  },
  parent: {
    fullName: 'Tasha Carter',
    email: 'tasha.parent@example.com',
    phone: '513-555-0108',
    category: 'Parent/Guardian',
    interest: 'Enrolling my son',
    source: 'website-intake',
    consent: true,
    message: 'Interested in signing my son up for the YEP Process.',
  },
  youngAdult: {
    fullName: 'Marcus Reed',
    email: 'marcus.ya@example.com',
    phone: '5135550110',
    age: 21,
    category: 'Young Adult',
    interest: 'Entrepreneurship track',
    source: 'website-intake',
    consent: 'on',
    message: 'Looking to build my hustle through Y-A.E.P.',
  },
  mentor: {
    fullName: 'Denise Howard',
    email: 'denise.mentor@example.com',
    phone: '+15135550112',
    category: 'Mentor',
    interest: 'Mentoring teens',
    source: 'volunteer-page',
    consent: true,
    message: '10 years coaching youth; would love to mentor a cohort.',
  },
  volunteer: {
    fullName: 'Greg Patterson',
    email: 'greg.volunteer@example.com',
    phone: '513.555.0114',
    category: 'Volunteer',
    interest: 'Event support',
    source: 'volunteer-page',
    consent: 'yes',
    message: 'Available weekends to help with events.',
  },
  sponsor: {
    fullName: 'Linda Okafor',
    email: 'linda.sponsor@example.com',
    phone: '5135550116',
    category: 'Sponsor',
    interest: 'Funding workbooks',
    source: 'sponsor-outreach',
    consent: true,
    message: 'Our company would like to sponsor a cohort this year.',
  },
  partner: {
    fullName: 'Bright Futures CDC',
    email: 'partner@brightfutures.example.com',
    phone: '5135550118',
    category: 'Partner',
    interest: 'Community partnership',
    source: 'partner-outreach',
    consent: true,
    message: 'Exploring a referral partnership for local youth.',
  },
  general: {
    fullName: 'Sam Rivera',
    email: 'sam.general@example.com',
    phone: '5135550120',
    category: 'General',
    interest: 'General question',
    source: 'contact-form',
    consent: true,
    message: 'How does the YEP Process work?',
  },
};

export const payloadList = Object.entries(payloads).map(([key, body]) => ({ key, body }));
